//Types of actions to manage redux reducers
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const SET_PRODUCT_ID = 'SET_PRODUCT_ID';
export const GET_PRODUCT_ID = 'GET PRODUCT_ID';
export const SET_PRODUCT_MODAL_FOR_ORDER = 'SET_PRODUCT_MODAL_FOR_ORDER';

export const GET_USERORDERS = 'GET_USERORDERS';
export const ADD_USERORDER = 'ADD_USERORDER';
export const GET_USERORDER = 'GET_USERORDER';
export const DELETE_USERORDER = 'DELETE_USERORDER';
export const USERORDERS_LOADING = 'USERORDERS_LOADING';
export const SET_USERORDER_ID = 'SET_USERORDER_ID';
export const SET_USERORDER_NAME = 'SET_USERORDER_NAME';
export const GET_USERORDER_ID = 'GET_USERORDER_ID';
export const GET_USERORDER_NAME = 'GET_USERORDER_NAME';
export const SET_USERORDER_INFO = 'SET_USERORDER_INFO';
export const GET_USERORDER_INFO = 'GET_USERORDER_INFO';

export const GET_ORDERS = 'GET_ORDERS';
export const ADD_ORDER = 'ADD_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';
export const ORDERS_LOADING = 'ORDERS_LOADING';
export const ORDER_QUANTITY_ERROR = 'ORDER_QUANTITY_ERROR';

export const SIGNUP = 'SIGNUP';
export const SIGNIN = 'SIGNIN';
export const SIGNOUT = 'SIGNOUT';
export const GET_TOKEN = 'GET_TOKEN';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const GET_AUTH_ERROR = 'GET_AUTH_ERROR';
export const SET_SIGN_UP_ERROR = 'SET_SIGN_UP_ERROR';